// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA745yGHXQZ4leNLBPhObKdE-3GFzZJ-bI',
    appId: '1:529015739148:web:0479dc9134efa3b1d8af29',
    messagingSenderId: '529015739148',
    projectId: 'captain-o360',
    authDomain: 'captain-o360.firebaseapp.com',
    storageBucket: 'captain-o360.firebasestorage.app',
    measurementId: 'G-D63BW9PGYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQEus4UX05PmRZ5Jhb39VgzaGgk9oCL-0',
    appId: '1:529015739148:android:68f61744944b0296d8af29',
    messagingSenderId: '529015739148',
    projectId: 'captain-o360',
    storageBucket: 'captain-o360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-jc5qa5_AUs5JVTnfY3hfUnOaja2E6g',
    appId: '1:529015739148:ios:be7e586377fae35dd8af29',
    messagingSenderId: '529015739148',
    projectId: 'captain-o360',
    storageBucket: 'captain-o360.firebasestorage.app',
    iosBundleId: 'com.orbipay.test8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA745yGHXQZ4leNLBPhObKdE-3GFzZJ-bI',
    appId: '1:529015739148:web:5fcaca293783cabcd8af29',
    messagingSenderId: '529015739148',
    projectId: 'captain-o360',
    authDomain: 'captain-o360.firebaseapp.com',
    storageBucket: 'captain-o360.firebasestorage.app',
    measurementId: 'G-70M4ZH6RDB',
  );
}
