// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'billnogenerator/BillCounter.dart';
import 'models/menu_item.dart';
import 'models/transaction.dart';
import 'table_selection/tabledata.dart';
import 'udhari/udharicustomer.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1946107522687558548),
    name: 'BillCounter',
    lastPropertyId: const obx_int.IdUid(14, 6334187345324838075),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6896504737781255785),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3493723725555546193),
        name: 'lastBillNo',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3652927155827169365),
        name: 'reserved_field',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 890619093528312970),
        name: 'reserved_field1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6055694307514867168),
        name: 'reserved_field2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4818164239551662687),
        name: 'reserved_field3',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3171097577670058620),
        name: 'reserved_field4',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6334187345324838075),
        name: 'reserved_field5',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8114204961835078834),
    name: 'MenuItem',
    lastPropertyId: const obx_int.IdUid(47, 8025367918054177096),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 802512363757854058),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4979957432532470950),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7626383289215904474),
        name: 'sellPrice',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2556521518139858627),
        name: 'sellPriceType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1058023457713317961),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3974065259738102374),
        name: 'mrp',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2746531864583793098),
        name: 'purchasePrice',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 270000371187691323),
        name: 'acSellPrice',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5729941685397430114),
        name: 'nonAcSellPrice',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3518267749100793414),
        name: 'onlineDeliveryPrice',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2223437056652204869),
        name: 'onlineSellPrice',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6913116738695704523),
        name: 'hsnCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7481078827017185573),
        name: 'itemCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4582097409744723322),
        name: 'barCode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4503745628639874326),
        name: 'barCode2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7795568996134466931),
        name: 'imagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 3728742540332773193),
        name: 'available',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3709452726156369209),
        name: 'adjustStock',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 2401209058082671043),
        name: 'gstRate',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 5931276234318032144),
        name: 'withTax',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(21, 8601631957554148333),
        name: 'cessRate',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(22, 5527740889673727068),
        name: 'selected',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 239290872055990391),
        name: 'qty',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 7192596659275377434),
        name: 'h_price',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 3101615149014389525),
        name: 'f_price',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 6088582964735282740),
        name: 'favorites',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 2335499788980328208),
        name: 'selectedprice',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(29, 2133796381418258809),
        name: 'H_portion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(30, 1696512192745594327),
        name: 'F_portion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(31, 1444400076070810449),
        name: 'h_qty',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(32, 7028628005008395310),
        name: 'acSellPriceHalf',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(33, 4923964005978581475),
        name: 'nonAcSellPriceHalf',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(34, 3246484421774456385),
        name: 'onlineDeliveryPriceHalf',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(35, 7387153495941634258),
        name: 'onlineSellPriceHalf',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(42, 3904168566259483046),
        name: 'reserved_field',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(43, 5545264522990096364),
        name: 'reserved_field1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(44, 1193250971417611750),
        name: 'reserved_field2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(45, 8058901824592232407),
        name: 'reserved_field3',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(46, 9047182738703218607),
        name: 'reserved_field4',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(47, 8025367918054177096),
        name: 'reserved_field5',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 4469350567211994079),
    name: 'Transaction',
    lastPropertyId: const obx_int.IdUid(28, 45478420937704277),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8131009903074985169),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4782203889573263965),
        name: 'time',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2458118208397326765),
        name: 'tableNo',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7509892375085753678),
        name: 'total',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7018620893989278948),
        name: 'cartData',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 15785753931824965),
        name: 'payment_mode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1789677029864079247),
        name: 'synced',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6459308640868403761),
        name: 'status',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4329541305353085393),
        name: 'serviceCharge',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6713194742888200),
        name: 'discount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1490224461369350918),
        name: 'discountPercent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2843372893312144744),
        name: 'billNo',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 473879555726256088),
        name: 'customerName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 136601896720739481),
        name: 'mobileNo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 8294844815105658188),
        name: 'reserved',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(23, 1811143835199410385),
        name: 'reserved_field',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(24, 2181348677092506159),
        name: 'reserved_field1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(25, 3411401464753810407),
        name: 'reserved_field2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(26, 5331955767904873158),
        name: 'reserved_field3',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(27, 2650762349556302124),
        name: 'reserved_field4',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(28, 45478420937704277),
        name: 'reserved_field5',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 8243572385061020594),
    name: 'udhariCustomer',
    lastPropertyId: const obx_int.IdUid(12, 6332134424552111661),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8453394554945812347),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4012736884600220841),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6661380246559368639),
        name: 'phone',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3488280849196140420),
        name: 'adreess',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3282334087181252157),
        name: 'reserved_field',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3842315091163120335),
        name: 'reserved_field1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7509998229175443065),
        name: 'reserved_field2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6332134424552111661),
        name: 'reserved_field3',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'transactions',
        srcEntity: 'TransactionUdhari',
        srcField: 'customer',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 1884757268945243640),
    name: 'TransactionUdhari',
    lastPropertyId: const obx_int.IdUid(14, 5803474790427682343),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3898405725570303972),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1255829561908364101),
        name: 'amount',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5261077648478436059),
        name: 'date',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4380612195846160888),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1584331416331425118),
        name: 'customerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 6843802771522843606),
        relationField: 'customer',
        relationTarget: 'udhariCustomer',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5882108357253340408),
        name: 'typeIndex',
        type: 2,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6171959339297063102),
        name: 'reserved_field',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3552762795509009251),
        name: 'reserved_field1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7071786404374621386),
        name: 'reserved_field2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5803474790427682343),
        name: 'reserved_field3',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 803850883550001508),
    name: 'CartItem',
    lastPropertyId: const obx_int.IdUid(18, 2326055945279238616),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1537715861209270899),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7807157970619497908),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6205947687105942005),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7744907605469431459),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1002619936605644404),
        name: 'menuItemId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 5111844153902982217),
        relationField: 'menuItem',
        relationTarget: 'Active_Table_view',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5169526850648646553),
        name: 'reserved_field',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1020264955036171900),
        name: 'reserved_field1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6574452078128849705),
        name: 'reserved_field2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 6876608894670006487),
        name: 'reserved_field3',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 8155627079094188584),
        name: 'reserved_field4',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 2326055945279238616),
        name: 'reserved_field5',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 7003873532803288360),
    name: 'OrderItem',
    lastPropertyId: const obx_int.IdUid(18, 3444315800088588529),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2388451390502732195),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6999080145120660670),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3692947459759201416),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5210782169151502311),
        name: 'tableId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 689252794369788013),
        relationField: 'table',
        relationTarget: 'Active_Table_view',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7488097895585267064),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 424290092089091347),
        name: 'reserved_field',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1018494323053729231),
        name: 'reserved_field1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4896221720363075571),
        name: 'reserved_field2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3836507280902470351),
        name: 'reserved_field3',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 475226244958169496),
        name: 'reserved_field4',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 3444315800088588529),
        name: 'reserved_field5',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(12, 6667384983004949850),
    name: 'Active_Table_view',
    lastPropertyId: const obx_int.IdUid(16, 3125477720319417828),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8982810354995276672),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7851657016156138759),
        name: 'number',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(7, 5887073448237941227),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3590177778214797541),
        name: 'total',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8847254960704675750),
        name: 'paymentMethod',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5915319727339157987),
        name: 'reserved_field',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 3189806009134391283),
        name: 'reserved_field1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 4981511791043725531),
        name: 'reserved_field2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2058993428695702654),
        name: 'reserved_field3',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7832259321494686768),
        name: 'reserved_field4',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3125477720319417828),
        name: 'reserved_field5',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'orders',
        srcEntity: 'OrderItem',
        srcField: '',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(12, 6667384983004949850),
    lastIndexId: const obx_int.IdUid(7, 5887073448237941227),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      8854128581512957275,
      7974487275215316857,
      7049026563589320485,
      7501939051296568394,
    ],
    retiredIndexUids: const [2949884291810905225],
    retiredPropertyUids: const [
      2532719961100771210,
      2538120491707400509,
      2925587239166398918,
      2571438622807061744,
      7043066779296367492,
      2566802023181227123,
      613313834471928508,
      8788214548444100795,
      61289289537238665,
      7800526016126872158,
      4295646385006264821,
      3754122875983547612,
      2263718378666814959,
      4272125859236521333,
      7022538984778189296,
      6840904171017765899,
      3435686221136522241,
      3552243637992397625,
      6139848359760028549,
      440371670897365644,
      2723741359949647042,
      9022478703125113524,
      8508181141172326837,
      1728092481944742833,
      3250621795413944011,
      3345508732266614869,
      5077552047619262580,
      331195739380969709,
      1218191536249054997,
      7451862050169094102,
      3776492164374303478,
      333550421043987280,
      5376628577688000972,
      5631026064100859632,
      4562630642493802880,
      5771921125160875364,
      7399758215384875929,
      6953192275576639148,
      7394778357632798547,
      3843019129049879716,
      888500646566986864,
      5211137398883652487,
      8340799443803579650,
      1668797096378767991,
      6016334683333246844,
      1842858285247900859,
      5722165817705302782,
      9032767571641523738,
      553389984490629193,
      479115336456823566,
      6571728558552766296,
      8169574257252559520,
      7051356569234112686,
      406034958368150728,
      2911151615343145257,
      5929159573409088983,
      8637785427299406276,
      6720286854143728436,
      1117714632674622873,
      1268417130193601446,
      1091485719071189523,
      1568387045619338153,
      84744643200870017,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    BillCounter: obx_int.EntityDefinition<BillCounter>(
      model: _entities[0],
      toOneRelations: (BillCounter object) => [],
      toManyRelations: (BillCounter object) => {},
      getId: (BillCounter object) => object.id,
      setId: (BillCounter object, int id) {
        object.id = id;
      },
      objectToFB: (BillCounter object, fb.Builder fbb) {
        final reserved_fieldOffset = object.reserved_field == null
            ? null
            : fbb.writeString(object.reserved_field!);
        final reserved_field1Offset = object.reserved_field1 == null
            ? null
            : fbb.writeString(object.reserved_field1!);
        final reserved_field2Offset = object.reserved_field2 == null
            ? null
            : fbb.writeString(object.reserved_field2!);
        final reserved_field3Offset = object.reserved_field3 == null
            ? null
            : fbb.writeString(object.reserved_field3!);
        final reserved_field4Offset = object.reserved_field4 == null
            ? null
            : fbb.writeString(object.reserved_field4!);
        final reserved_field5Offset = object.reserved_field5 == null
            ? null
            : fbb.writeString(object.reserved_field5!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.lastBillNo);
        fbb.addOffset(8, reserved_fieldOffset);
        fbb.addOffset(9, reserved_field1Offset);
        fbb.addOffset(10, reserved_field2Offset);
        fbb.addOffset(11, reserved_field3Offset);
        fbb.addOffset(12, reserved_field4Offset);
        fbb.addOffset(13, reserved_field5Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastBillNoParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final reserved_fieldParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final reserved_field1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final reserved_field2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final reserved_field3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final reserved_field4Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final reserved_field5Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final object = BillCounter(
          lastBillNo: lastBillNoParam,
          reserved_field: reserved_fieldParam,
          reserved_field1: reserved_field1Param,
          reserved_field2: reserved_field2Param,
          reserved_field3: reserved_field3Param,
          reserved_field4: reserved_field4Param,
          reserved_field5: reserved_field5Param,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    MenuItem: obx_int.EntityDefinition<MenuItem>(
      model: _entities[1],
      toOneRelations: (MenuItem object) => [],
      toManyRelations: (MenuItem object) => {},
      getId: (MenuItem object) => object.id,
      setId: (MenuItem object, int id) {
        object.id = id;
      },
      objectToFB: (MenuItem object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final sellPriceOffset = fbb.writeString(object.sellPrice);
        final sellPriceTypeOffset = fbb.writeString(object.sellPriceType);
        final categoryOffset = fbb.writeString(object.category);
        final mrpOffset = object.mrp == null
            ? null
            : fbb.writeString(object.mrp!);
        final purchasePriceOffset = object.purchasePrice == null
            ? null
            : fbb.writeString(object.purchasePrice!);
        final acSellPriceOffset = object.acSellPrice == null
            ? null
            : fbb.writeString(object.acSellPrice!);
        final nonAcSellPriceOffset = object.nonAcSellPrice == null
            ? null
            : fbb.writeString(object.nonAcSellPrice!);
        final onlineDeliveryPriceOffset = object.onlineDeliveryPrice == null
            ? null
            : fbb.writeString(object.onlineDeliveryPrice!);
        final onlineSellPriceOffset = object.onlineSellPrice == null
            ? null
            : fbb.writeString(object.onlineSellPrice!);
        final hsnCodeOffset = object.hsnCode == null
            ? null
            : fbb.writeString(object.hsnCode!);
        final itemCodeOffset = object.itemCode == null
            ? null
            : fbb.writeString(object.itemCode!);
        final barCodeOffset = object.barCode == null
            ? null
            : fbb.writeString(object.barCode!);
        final barCode2Offset = object.barCode2 == null
            ? null
            : fbb.writeString(object.barCode2!);
        final imagePathOffset = object.imagePath == null
            ? null
            : fbb.writeString(object.imagePath!);
        final h_priceOffset = object.h_price == null
            ? null
            : fbb.writeString(object.h_price!);
        final f_priceOffset = object.f_price == null
            ? null
            : fbb.writeString(object.f_price!);
        final H_portionOffset = object.H_portion == null
            ? null
            : fbb.writeString(object.H_portion!);
        final F_portionOffset = object.F_portion == null
            ? null
            : fbb.writeString(object.F_portion!);
        final acSellPriceHalfOffset = object.acSellPriceHalf == null
            ? null
            : fbb.writeString(object.acSellPriceHalf!);
        final nonAcSellPriceHalfOffset = object.nonAcSellPriceHalf == null
            ? null
            : fbb.writeString(object.nonAcSellPriceHalf!);
        final onlineDeliveryPriceHalfOffset =
            object.onlineDeliveryPriceHalf == null
            ? null
            : fbb.writeString(object.onlineDeliveryPriceHalf!);
        final onlineSellPriceHalfOffset = object.onlineSellPriceHalf == null
            ? null
            : fbb.writeString(object.onlineSellPriceHalf!);
        final reserved_fieldOffset = object.reserved_field == null
            ? null
            : fbb.writeString(object.reserved_field!);
        final reserved_field1Offset = object.reserved_field1 == null
            ? null
            : fbb.writeString(object.reserved_field1!);
        final reserved_field2Offset = object.reserved_field2 == null
            ? null
            : fbb.writeString(object.reserved_field2!);
        final reserved_field3Offset = object.reserved_field3 == null
            ? null
            : fbb.writeString(object.reserved_field3!);
        final reserved_field4Offset = object.reserved_field4 == null
            ? null
            : fbb.writeString(object.reserved_field4!);
        final reserved_field5Offset = object.reserved_field5 == null
            ? null
            : fbb.writeString(object.reserved_field5!);
        fbb.startTable(48);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, sellPriceOffset);
        fbb.addOffset(3, sellPriceTypeOffset);
        fbb.addOffset(4, categoryOffset);
        fbb.addOffset(5, mrpOffset);
        fbb.addOffset(6, purchasePriceOffset);
        fbb.addOffset(7, acSellPriceOffset);
        fbb.addOffset(8, nonAcSellPriceOffset);
        fbb.addOffset(9, onlineDeliveryPriceOffset);
        fbb.addOffset(10, onlineSellPriceOffset);
        fbb.addOffset(11, hsnCodeOffset);
        fbb.addOffset(12, itemCodeOffset);
        fbb.addOffset(13, barCodeOffset);
        fbb.addOffset(14, barCode2Offset);
        fbb.addOffset(15, imagePathOffset);
        fbb.addInt64(16, object.available);
        fbb.addInt64(17, object.adjustStock);
        fbb.addFloat64(18, object.gstRate);
        fbb.addBool(19, object.withTax);
        fbb.addFloat64(20, object.cessRate);
        fbb.addBool(21, object.selected);
        fbb.addInt64(22, object.qty);
        fbb.addOffset(23, h_priceOffset);
        fbb.addOffset(24, f_priceOffset);
        fbb.addBool(25, object.favorites);
        fbb.addInt64(27, object.selectedprice);
        fbb.addOffset(28, H_portionOffset);
        fbb.addOffset(29, F_portionOffset);
        fbb.addInt64(30, object.h_qty);
        fbb.addOffset(31, acSellPriceHalfOffset);
        fbb.addOffset(32, nonAcSellPriceHalfOffset);
        fbb.addOffset(33, onlineDeliveryPriceHalfOffset);
        fbb.addOffset(34, onlineSellPriceHalfOffset);
        fbb.addOffset(41, reserved_fieldOffset);
        fbb.addOffset(42, reserved_field1Offset);
        fbb.addOffset(43, reserved_field2Offset);
        fbb.addOffset(44, reserved_field3Offset);
        fbb.addOffset(45, reserved_field4Offset);
        fbb.addOffset(46, reserved_field5Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sellPriceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sellPriceTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final mrpParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final purchasePriceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final acSellPriceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final acSellPriceHalfParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 66);
        final nonAcSellPriceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final nonAcSellPriceHalfParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 68);
        final onlineDeliveryPriceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final onlineDeliveryPriceHalfParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 70);
        final onlineSellPriceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final onlineSellPriceHalfParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 72);
        final hsnCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final itemCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final barCodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final barCode2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final imagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final availableParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          36,
        );
        final adjustStockParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          38,
        );
        final gstRateParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          40,
        );
        final withTaxParam = const fb.BoolReader().vTableGetNullable(
          buffer,
          rootOffset,
          42,
        );
        final cessRateParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          44,
        );
        final selectedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          46,
          false,
        );
        final qtyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          48,
          0,
        );
        final h_qtyParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          64,
          0,
        );
        final f_priceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 52);
        final h_priceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final H_portionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 60);
        final F_portionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 62);
        final selectedpriceParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          58,
        );
        final favoritesParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          54,
          false,
        );
        final reserved_fieldParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 86);
        final reserved_field1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 88);
        final reserved_field2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 90);
        final reserved_field3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 92);
        final reserved_field4Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 94);
        final reserved_field5Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 96);
        final object = MenuItem(
          id: idParam,
          name: nameParam,
          sellPrice: sellPriceParam,
          sellPriceType: sellPriceTypeParam,
          category: categoryParam,
          mrp: mrpParam,
          purchasePrice: purchasePriceParam,
          acSellPrice: acSellPriceParam,
          acSellPriceHalf: acSellPriceHalfParam,
          nonAcSellPrice: nonAcSellPriceParam,
          nonAcSellPriceHalf: nonAcSellPriceHalfParam,
          onlineDeliveryPrice: onlineDeliveryPriceParam,
          onlineDeliveryPriceHalf: onlineDeliveryPriceHalfParam,
          onlineSellPrice: onlineSellPriceParam,
          onlineSellPriceHalf: onlineSellPriceHalfParam,
          hsnCode: hsnCodeParam,
          itemCode: itemCodeParam,
          barCode: barCodeParam,
          barCode2: barCode2Param,
          imagePath: imagePathParam,
          available: availableParam,
          adjustStock: adjustStockParam,
          gstRate: gstRateParam,
          withTax: withTaxParam,
          cessRate: cessRateParam,
          selected: selectedParam,
          qty: qtyParam,
          h_qty: h_qtyParam,
          f_price: f_priceParam,
          h_price: h_priceParam,
          H_portion: H_portionParam,
          F_portion: F_portionParam,
          selectedprice: selectedpriceParam,
          favorites: favoritesParam,
          reserved_field: reserved_fieldParam,
          reserved_field1: reserved_field1Param,
          reserved_field2: reserved_field2Param,
          reserved_field3: reserved_field3Param,
          reserved_field4: reserved_field4Param,
          reserved_field5: reserved_field5Param,
        );

        return object;
      },
    ),
    Transaction: obx_int.EntityDefinition<Transaction>(
      model: _entities[2],
      toOneRelations: (Transaction object) => [],
      toManyRelations: (Transaction object) => {},
      getId: (Transaction object) => object.id,
      setId: (Transaction object, int id) {
        object.id = id;
      },
      objectToFB: (Transaction object, fb.Builder fbb) {
        final cartDataOffset = fbb.writeString(object.cartData);
        final payment_modeOffset = fbb.writeString(object.payment_mode);
        final statusOffset = fbb.writeString(object.status);
        final customerNameOffset = object.customerName == null
            ? null
            : fbb.writeString(object.customerName!);
        final mobileNoOffset = object.mobileNo == null
            ? null
            : fbb.writeString(object.mobileNo!);
        final reservedOffset = object.reserved == null
            ? null
            : fbb.writeString(object.reserved!);
        final reserved_fieldOffset = object.reserved_field == null
            ? null
            : fbb.writeString(object.reserved_field!);
        final reserved_field1Offset = object.reserved_field1 == null
            ? null
            : fbb.writeString(object.reserved_field1!);
        final reserved_field2Offset = object.reserved_field2 == null
            ? null
            : fbb.writeString(object.reserved_field2!);
        final reserved_field3Offset = object.reserved_field3 == null
            ? null
            : fbb.writeString(object.reserved_field3!);
        final reserved_field4Offset = object.reserved_field4 == null
            ? null
            : fbb.writeString(object.reserved_field4!);
        final reserved_field5Offset = object.reserved_field5 == null
            ? null
            : fbb.writeString(object.reserved_field5!);
        fbb.startTable(29);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.time.millisecondsSinceEpoch);
        fbb.addInt64(2, object.tableNo);
        fbb.addInt64(3, object.total);
        fbb.addOffset(4, cartDataOffset);
        fbb.addOffset(5, payment_modeOffset);
        fbb.addBool(6, object.synced);
        fbb.addOffset(7, statusOffset);
        fbb.addFloat64(9, object.serviceCharge);
        fbb.addFloat64(10, object.discount);
        fbb.addFloat64(11, object.discountPercent);
        fbb.addInt64(12, object.billNo);
        fbb.addOffset(13, customerNameOffset);
        fbb.addOffset(14, mobileNoOffset);
        fbb.addOffset(15, reservedOffset);
        fbb.addOffset(22, reserved_fieldOffset);
        fbb.addOffset(23, reserved_field1Offset);
        fbb.addOffset(24, reserved_field2Offset);
        fbb.addOffset(25, reserved_field3Offset);
        fbb.addOffset(26, reserved_field4Offset);
        fbb.addOffset(27, reserved_field5Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final timeParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0),
        );
        final tableNoParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          8,
        );
        final totalParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final cartDataParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final payment_modeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final syncedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          16,
          false,
        );
        final statusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final serviceChargeParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          22,
        );
        final discountParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final discountPercentParam = const fb.Float64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final billNoParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          28,
        );
        final customerNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final mobileNoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final reservedParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final reserved_fieldParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 48);
        final reserved_field1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 50);
        final reserved_field2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 52);
        final reserved_field3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 54);
        final reserved_field4Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 56);
        final reserved_field5Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 58);
        final object = Transaction(
          time: timeParam,
          tableNo: tableNoParam,
          total: totalParam,
          cartData: cartDataParam,
          payment_mode: payment_modeParam,
          synced: syncedParam,
          status: statusParam,
          serviceCharge: serviceChargeParam,
          discount: discountParam,
          discountPercent: discountPercentParam,
          billNo: billNoParam,
          customerName: customerNameParam,
          mobileNo: mobileNoParam,
          reserved: reservedParam,
          reserved_field: reserved_fieldParam,
          reserved_field1: reserved_field1Param,
          reserved_field2: reserved_field2Param,
          reserved_field3: reserved_field3Param,
          reserved_field4: reserved_field4Param,
          reserved_field5: reserved_field5Param,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    udhariCustomer: obx_int.EntityDefinition<udhariCustomer>(
      model: _entities[3],
      toOneRelations: (udhariCustomer object) => [],
      toManyRelations: (udhariCustomer object) => {
        obx_int.RelInfo<TransactionUdhari>.toOneBacklink(
          5,
          object.id,
          (TransactionUdhari srcObject) => srcObject.customer,
        ): object.transactions,
      },
      getId: (udhariCustomer object) => object.id,
      setId: (udhariCustomer object, int id) {
        object.id = id;
      },
      objectToFB: (udhariCustomer object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final phoneOffset = fbb.writeString(object.phone);
        final adreessOffset = object.adreess == null
            ? null
            : fbb.writeString(object.adreess!);
        final reserved_fieldOffset = object.reserved_field == null
            ? null
            : fbb.writeString(object.reserved_field!);
        final reserved_field1Offset = object.reserved_field1 == null
            ? null
            : fbb.writeString(object.reserved_field1!);
        final reserved_field2Offset = object.reserved_field2 == null
            ? null
            : fbb.writeString(object.reserved_field2!);
        final reserved_field3Offset = object.reserved_field3 == null
            ? null
            : fbb.writeString(object.reserved_field3!);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, phoneOffset);
        fbb.addOffset(3, adreessOffset);
        fbb.addOffset(8, reserved_fieldOffset);
        fbb.addOffset(9, reserved_field1Offset);
        fbb.addOffset(10, reserved_field2Offset);
        fbb.addOffset(11, reserved_field3Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final phoneParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final adreessParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final reserved_fieldParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final reserved_field1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final reserved_field2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final reserved_field3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final object = udhariCustomer(
          name: nameParam,
          phone: phoneParam,
          adreess: adreessParam,
          reserved_field: reserved_fieldParam,
          reserved_field1: reserved_field1Param,
          reserved_field2: reserved_field2Param,
          reserved_field3: reserved_field3Param,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<udhariCustomer>(
          object.transactions,
          store,
          obx_int.RelInfo<TransactionUdhari>.toOneBacklink(
            5,
            object.id,
            (TransactionUdhari srcObject) => srcObject.customer,
          ),
        );
        return object;
      },
    ),
    TransactionUdhari: obx_int.EntityDefinition<TransactionUdhari>(
      model: _entities[4],
      toOneRelations: (TransactionUdhari object) => [object.customer],
      toManyRelations: (TransactionUdhari object) => {},
      getId: (TransactionUdhari object) => object.id,
      setId: (TransactionUdhari object, int id) {
        object.id = id;
      },
      objectToFB: (TransactionUdhari object, fb.Builder fbb) {
        final descriptionOffset = fbb.writeString(object.description);
        final reserved_fieldOffset = object.reserved_field == null
            ? null
            : fbb.writeString(object.reserved_field!);
        final reserved_field1Offset = object.reserved_field1 == null
            ? null
            : fbb.writeString(object.reserved_field1!);
        final reserved_field2Offset = object.reserved_field2 == null
            ? null
            : fbb.writeString(object.reserved_field2!);
        final reserved_field3Offset = object.reserved_field3 == null
            ? null
            : fbb.writeString(object.reserved_field3!);
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.amount);
        fbb.addInt64(2, object.date.millisecondsSinceEpoch);
        fbb.addOffset(3, descriptionOffset);
        fbb.addInt64(4, object.customer.targetId);
        fbb.addInt8(5, object.typeIndex);
        fbb.addOffset(10, reserved_fieldOffset);
        fbb.addOffset(11, reserved_field1Offset);
        fbb.addOffset(12, reserved_field2Offset);
        fbb.addOffset(13, reserved_field3Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = TransactionUdhari()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..amount = const fb.Float64Reader().vTableGet(
            buffer,
            rootOffset,
            6,
            0,
          )
          ..date = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..typeIndex = const fb.Int8Reader().vTableGet(
            buffer,
            rootOffset,
            14,
            0,
          )
          ..reserved_field = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 24)
          ..reserved_field1 = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 26)
          ..reserved_field2 = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 28)
          ..reserved_field3 = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 30);
        object.customer.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.customer.attach(store);
        return object;
      },
    ),
    CartItem: obx_int.EntityDefinition<CartItem>(
      model: _entities[5],
      toOneRelations: (CartItem object) => [object.menuItem],
      toManyRelations: (CartItem object) => {},
      getId: (CartItem object) => object.id,
      setId: (CartItem object, int id) {
        object.id = id;
      },
      objectToFB: (CartItem object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final reserved_fieldOffset = object.reserved_field == null
            ? null
            : fbb.writeString(object.reserved_field!);
        final reserved_field1Offset = object.reserved_field1 == null
            ? null
            : fbb.writeString(object.reserved_field1!);
        final reserved_field2Offset = object.reserved_field2 == null
            ? null
            : fbb.writeString(object.reserved_field2!);
        final reserved_field3Offset = object.reserved_field3 == null
            ? null
            : fbb.writeString(object.reserved_field3!);
        final reserved_field4Offset = object.reserved_field4 == null
            ? null
            : fbb.writeString(object.reserved_field4!);
        final reserved_field5Offset = object.reserved_field5 == null
            ? null
            : fbb.writeString(object.reserved_field5!);
        fbb.startTable(19);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.quantity);
        fbb.addOffset(2, nameOffset);
        fbb.addFloat64(3, object.price);
        fbb.addInt64(5, object.menuItem.targetId);
        fbb.addOffset(12, reserved_fieldOffset);
        fbb.addOffset(13, reserved_field1Offset);
        fbb.addOffset(14, reserved_field2Offset);
        fbb.addOffset(15, reserved_field3Offset);
        fbb.addOffset(16, reserved_field4Offset);
        fbb.addOffset(17, reserved_field5Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final reserved_fieldParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final reserved_field1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final reserved_field2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final reserved_field3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final reserved_field4Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final reserved_field5Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final object = CartItem(
          name: nameParam,
          price: priceParam,
          quantity: quantityParam,
          reserved_field: reserved_fieldParam,
          reserved_field1: reserved_field1Param,
          reserved_field2: reserved_field2Param,
          reserved_field3: reserved_field3Param,
          reserved_field4: reserved_field4Param,
          reserved_field5: reserved_field5Param,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.menuItem.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.menuItem.attach(store);
        return object;
      },
    ),
    OrderItem: obx_int.EntityDefinition<OrderItem>(
      model: _entities[6],
      toOneRelations: (OrderItem object) => [object.table],
      toManyRelations: (OrderItem object) => {},
      getId: (OrderItem object) => object.id,
      setId: (OrderItem object, int id) {
        object.id = id;
      },
      objectToFB: (OrderItem object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final reserved_fieldOffset = object.reserved_field == null
            ? null
            : fbb.writeString(object.reserved_field!);
        final reserved_field1Offset = object.reserved_field1 == null
            ? null
            : fbb.writeString(object.reserved_field1!);
        final reserved_field2Offset = object.reserved_field2 == null
            ? null
            : fbb.writeString(object.reserved_field2!);
        final reserved_field3Offset = object.reserved_field3 == null
            ? null
            : fbb.writeString(object.reserved_field3!);
        final reserved_field4Offset = object.reserved_field4 == null
            ? null
            : fbb.writeString(object.reserved_field4!);
        final reserved_field5Offset = object.reserved_field5 == null
            ? null
            : fbb.writeString(object.reserved_field5!);
        fbb.startTable(19);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addFloat64(3, object.price);
        fbb.addInt64(4, object.table.targetId);
        fbb.addInt64(5, object.quantity);
        fbb.addOffset(12, reserved_fieldOffset);
        fbb.addOffset(13, reserved_field1Offset);
        fbb.addOffset(14, reserved_field2Offset);
        fbb.addOffset(15, reserved_field3Offset);
        fbb.addOffset(16, reserved_field4Offset);
        fbb.addOffset(17, reserved_field5Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final reserved_fieldParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final reserved_field1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final reserved_field2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final reserved_field3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final reserved_field4Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final reserved_field5Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 38);
        final object = OrderItem(
          name: nameParam,
          quantity: quantityParam,
          price: priceParam,
          reserved_field: reserved_fieldParam,
          reserved_field1: reserved_field1Param,
          reserved_field2: reserved_field2Param,
          reserved_field3: reserved_field3Param,
          reserved_field4: reserved_field4Param,
          reserved_field5: reserved_field5Param,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.table.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.table.attach(store);
        return object;
      },
    ),
    Active_Table_view: obx_int.EntityDefinition<Active_Table_view>(
      model: _entities[7],
      toOneRelations: (Active_Table_view object) => [],
      toManyRelations: (Active_Table_view object) => {
        obx_int.RelInfo<OrderItem>.toOneBacklink(
          5,
          object.id,
          (OrderItem srcObject) => srcObject.table,
        ): object.orders,
      },
      getId: (Active_Table_view object) => object.id,
      setId: (Active_Table_view object, int id) {
        object.id = id;
      },
      objectToFB: (Active_Table_view object, fb.Builder fbb) {
        final paymentMethodOffset = fbb.writeString(object.paymentMethod);
        final reserved_fieldOffset = object.reserved_field == null
            ? null
            : fbb.writeString(object.reserved_field!);
        final reserved_field1Offset = object.reserved_field1 == null
            ? null
            : fbb.writeString(object.reserved_field1!);
        final reserved_field2Offset = object.reserved_field2 == null
            ? null
            : fbb.writeString(object.reserved_field2!);
        final reserved_field3Offset = object.reserved_field3 == null
            ? null
            : fbb.writeString(object.reserved_field3!);
        final reserved_field4Offset = object.reserved_field4 == null
            ? null
            : fbb.writeString(object.reserved_field4!);
        final reserved_field5Offset = object.reserved_field5 == null
            ? null
            : fbb.writeString(object.reserved_field5!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.number);
        fbb.addFloat64(2, object.total);
        fbb.addOffset(3, paymentMethodOffset);
        fbb.addOffset(10, reserved_fieldOffset);
        fbb.addOffset(11, reserved_field1Offset);
        fbb.addOffset(12, reserved_field2Offset);
        fbb.addOffset(13, reserved_field3Offset);
        fbb.addOffset(14, reserved_field4Offset);
        fbb.addOffset(15, reserved_field5Offset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final numberParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final totalParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final paymentMethodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final reserved_fieldParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final reserved_field1Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final reserved_field2Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final reserved_field3Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final reserved_field4Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final reserved_field5Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final object = Active_Table_view(
          number: numberParam,
          total: totalParam,
          paymentMethod: paymentMethodParam,
          reserved_field: reserved_fieldParam,
          reserved_field1: reserved_field1Param,
          reserved_field2: reserved_field2Param,
          reserved_field3: reserved_field3Param,
          reserved_field4: reserved_field4Param,
          reserved_field5: reserved_field5Param,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<Active_Table_view>(
          object.orders,
          store,
          obx_int.RelInfo<OrderItem>.toOneBacklink(
            5,
            object.id,
            (OrderItem srcObject) => srcObject.table,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BillCounter] entity fields to define ObjectBox queries.
class BillCounter_ {
  /// See [BillCounter.id].
  static final id = obx.QueryIntegerProperty<BillCounter>(
    _entities[0].properties[0],
  );

  /// See [BillCounter.lastBillNo].
  static final lastBillNo = obx.QueryIntegerProperty<BillCounter>(
    _entities[0].properties[1],
  );

  /// See [BillCounter.reserved_field].
  static final reserved_field = obx.QueryStringProperty<BillCounter>(
    _entities[0].properties[2],
  );

  /// See [BillCounter.reserved_field1].
  static final reserved_field1 = obx.QueryStringProperty<BillCounter>(
    _entities[0].properties[3],
  );

  /// See [BillCounter.reserved_field2].
  static final reserved_field2 = obx.QueryStringProperty<BillCounter>(
    _entities[0].properties[4],
  );

  /// See [BillCounter.reserved_field3].
  static final reserved_field3 = obx.QueryStringProperty<BillCounter>(
    _entities[0].properties[5],
  );

  /// See [BillCounter.reserved_field4].
  static final reserved_field4 = obx.QueryStringProperty<BillCounter>(
    _entities[0].properties[6],
  );

  /// See [BillCounter.reserved_field5].
  static final reserved_field5 = obx.QueryStringProperty<BillCounter>(
    _entities[0].properties[7],
  );
}

/// [MenuItem] entity fields to define ObjectBox queries.
class MenuItem_ {
  /// See [MenuItem.id].
  static final id = obx.QueryIntegerProperty<MenuItem>(
    _entities[1].properties[0],
  );

  /// See [MenuItem.name].
  static final name = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[1],
  );

  /// See [MenuItem.sellPrice].
  static final sellPrice = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[2],
  );

  /// See [MenuItem.sellPriceType].
  static final sellPriceType = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[3],
  );

  /// See [MenuItem.category].
  static final category = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[4],
  );

  /// See [MenuItem.mrp].
  static final mrp = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[5],
  );

  /// See [MenuItem.purchasePrice].
  static final purchasePrice = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[6],
  );

  /// See [MenuItem.acSellPrice].
  static final acSellPrice = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[7],
  );

  /// See [MenuItem.nonAcSellPrice].
  static final nonAcSellPrice = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[8],
  );

  /// See [MenuItem.onlineDeliveryPrice].
  static final onlineDeliveryPrice = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[9],
  );

  /// See [MenuItem.onlineSellPrice].
  static final onlineSellPrice = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[10],
  );

  /// See [MenuItem.hsnCode].
  static final hsnCode = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[11],
  );

  /// See [MenuItem.itemCode].
  static final itemCode = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[12],
  );

  /// See [MenuItem.barCode].
  static final barCode = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[13],
  );

  /// See [MenuItem.barCode2].
  static final barCode2 = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[14],
  );

  /// See [MenuItem.imagePath].
  static final imagePath = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[15],
  );

  /// See [MenuItem.available].
  static final available = obx.QueryIntegerProperty<MenuItem>(
    _entities[1].properties[16],
  );

  /// See [MenuItem.adjustStock].
  static final adjustStock = obx.QueryIntegerProperty<MenuItem>(
    _entities[1].properties[17],
  );

  /// See [MenuItem.gstRate].
  static final gstRate = obx.QueryDoubleProperty<MenuItem>(
    _entities[1].properties[18],
  );

  /// See [MenuItem.withTax].
  static final withTax = obx.QueryBooleanProperty<MenuItem>(
    _entities[1].properties[19],
  );

  /// See [MenuItem.cessRate].
  static final cessRate = obx.QueryDoubleProperty<MenuItem>(
    _entities[1].properties[20],
  );

  /// See [MenuItem.selected].
  static final selected = obx.QueryBooleanProperty<MenuItem>(
    _entities[1].properties[21],
  );

  /// See [MenuItem.qty].
  static final qty = obx.QueryIntegerProperty<MenuItem>(
    _entities[1].properties[22],
  );

  /// See [MenuItem.h_price].
  static final h_price = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[23],
  );

  /// See [MenuItem.f_price].
  static final f_price = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[24],
  );

  /// See [MenuItem.favorites].
  static final favorites = obx.QueryBooleanProperty<MenuItem>(
    _entities[1].properties[25],
  );

  /// See [MenuItem.selectedprice].
  static final selectedprice = obx.QueryIntegerProperty<MenuItem>(
    _entities[1].properties[26],
  );

  /// See [MenuItem.H_portion].
  static final H_portion = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[27],
  );

  /// See [MenuItem.F_portion].
  static final F_portion = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[28],
  );

  /// See [MenuItem.h_qty].
  static final h_qty = obx.QueryIntegerProperty<MenuItem>(
    _entities[1].properties[29],
  );

  /// See [MenuItem.acSellPriceHalf].
  static final acSellPriceHalf = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[30],
  );

  /// See [MenuItem.nonAcSellPriceHalf].
  static final nonAcSellPriceHalf = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[31],
  );

  /// See [MenuItem.onlineDeliveryPriceHalf].
  static final onlineDeliveryPriceHalf = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[32],
  );

  /// See [MenuItem.onlineSellPriceHalf].
  static final onlineSellPriceHalf = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[33],
  );

  /// See [MenuItem.reserved_field].
  static final reserved_field = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[34],
  );

  /// See [MenuItem.reserved_field1].
  static final reserved_field1 = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[35],
  );

  /// See [MenuItem.reserved_field2].
  static final reserved_field2 = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[36],
  );

  /// See [MenuItem.reserved_field3].
  static final reserved_field3 = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[37],
  );

  /// See [MenuItem.reserved_field4].
  static final reserved_field4 = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[38],
  );

  /// See [MenuItem.reserved_field5].
  static final reserved_field5 = obx.QueryStringProperty<MenuItem>(
    _entities[1].properties[39],
  );
}

/// [Transaction] entity fields to define ObjectBox queries.
class Transaction_ {
  /// See [Transaction.id].
  static final id = obx.QueryIntegerProperty<Transaction>(
    _entities[2].properties[0],
  );

  /// See [Transaction.time].
  static final time = obx.QueryDateProperty<Transaction>(
    _entities[2].properties[1],
  );

  /// See [Transaction.tableNo].
  static final tableNo = obx.QueryIntegerProperty<Transaction>(
    _entities[2].properties[2],
  );

  /// See [Transaction.total].
  static final total = obx.QueryIntegerProperty<Transaction>(
    _entities[2].properties[3],
  );

  /// See [Transaction.cartData].
  static final cartData = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[4],
  );

  /// See [Transaction.payment_mode].
  static final payment_mode = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[5],
  );

  /// See [Transaction.synced].
  static final synced = obx.QueryBooleanProperty<Transaction>(
    _entities[2].properties[6],
  );

  /// See [Transaction.status].
  static final status = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[7],
  );

  /// See [Transaction.serviceCharge].
  static final serviceCharge = obx.QueryDoubleProperty<Transaction>(
    _entities[2].properties[8],
  );

  /// See [Transaction.discount].
  static final discount = obx.QueryDoubleProperty<Transaction>(
    _entities[2].properties[9],
  );

  /// See [Transaction.discountPercent].
  static final discountPercent = obx.QueryDoubleProperty<Transaction>(
    _entities[2].properties[10],
  );

  /// See [Transaction.billNo].
  static final billNo = obx.QueryIntegerProperty<Transaction>(
    _entities[2].properties[11],
  );

  /// See [Transaction.customerName].
  static final customerName = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[12],
  );

  /// See [Transaction.mobileNo].
  static final mobileNo = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[13],
  );

  /// See [Transaction.reserved].
  static final reserved = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[14],
  );

  /// See [Transaction.reserved_field].
  static final reserved_field = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[15],
  );

  /// See [Transaction.reserved_field1].
  static final reserved_field1 = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[16],
  );

  /// See [Transaction.reserved_field2].
  static final reserved_field2 = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[17],
  );

  /// See [Transaction.reserved_field3].
  static final reserved_field3 = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[18],
  );

  /// See [Transaction.reserved_field4].
  static final reserved_field4 = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[19],
  );

  /// See [Transaction.reserved_field5].
  static final reserved_field5 = obx.QueryStringProperty<Transaction>(
    _entities[2].properties[20],
  );
}

/// [udhariCustomer] entity fields to define ObjectBox queries.
class udhariCustomer_ {
  /// See [udhariCustomer.id].
  static final id = obx.QueryIntegerProperty<udhariCustomer>(
    _entities[3].properties[0],
  );

  /// See [udhariCustomer.name].
  static final name = obx.QueryStringProperty<udhariCustomer>(
    _entities[3].properties[1],
  );

  /// See [udhariCustomer.phone].
  static final phone = obx.QueryStringProperty<udhariCustomer>(
    _entities[3].properties[2],
  );

  /// See [udhariCustomer.adreess].
  static final adreess = obx.QueryStringProperty<udhariCustomer>(
    _entities[3].properties[3],
  );

  /// See [udhariCustomer.reserved_field].
  static final reserved_field = obx.QueryStringProperty<udhariCustomer>(
    _entities[3].properties[4],
  );

  /// See [udhariCustomer.reserved_field1].
  static final reserved_field1 = obx.QueryStringProperty<udhariCustomer>(
    _entities[3].properties[5],
  );

  /// See [udhariCustomer.reserved_field2].
  static final reserved_field2 = obx.QueryStringProperty<udhariCustomer>(
    _entities[3].properties[6],
  );

  /// See [udhariCustomer.reserved_field3].
  static final reserved_field3 = obx.QueryStringProperty<udhariCustomer>(
    _entities[3].properties[7],
  );

  /// see [udhariCustomer.transactions]
  static final transactions =
      obx.QueryBacklinkToMany<TransactionUdhari, udhariCustomer>(
        TransactionUdhari_.customer,
      );
}

/// [TransactionUdhari] entity fields to define ObjectBox queries.
class TransactionUdhari_ {
  /// See [TransactionUdhari.id].
  static final id = obx.QueryIntegerProperty<TransactionUdhari>(
    _entities[4].properties[0],
  );

  /// See [TransactionUdhari.amount].
  static final amount = obx.QueryDoubleProperty<TransactionUdhari>(
    _entities[4].properties[1],
  );

  /// See [TransactionUdhari.date].
  static final date = obx.QueryDateProperty<TransactionUdhari>(
    _entities[4].properties[2],
  );

  /// See [TransactionUdhari.description].
  static final description = obx.QueryStringProperty<TransactionUdhari>(
    _entities[4].properties[3],
  );

  /// See [TransactionUdhari.customer].
  static final customer =
      obx.QueryRelationToOne<TransactionUdhari, udhariCustomer>(
        _entities[4].properties[4],
      );

  /// See [TransactionUdhari.typeIndex].
  static final typeIndex = obx.QueryIntegerProperty<TransactionUdhari>(
    _entities[4].properties[5],
  );

  /// See [TransactionUdhari.reserved_field].
  static final reserved_field = obx.QueryStringProperty<TransactionUdhari>(
    _entities[4].properties[6],
  );

  /// See [TransactionUdhari.reserved_field1].
  static final reserved_field1 = obx.QueryStringProperty<TransactionUdhari>(
    _entities[4].properties[7],
  );

  /// See [TransactionUdhari.reserved_field2].
  static final reserved_field2 = obx.QueryStringProperty<TransactionUdhari>(
    _entities[4].properties[8],
  );

  /// See [TransactionUdhari.reserved_field3].
  static final reserved_field3 = obx.QueryStringProperty<TransactionUdhari>(
    _entities[4].properties[9],
  );
}

/// [CartItem] entity fields to define ObjectBox queries.
class CartItem_ {
  /// See [CartItem.id].
  static final id = obx.QueryIntegerProperty<CartItem>(
    _entities[5].properties[0],
  );

  /// See [CartItem.quantity].
  static final quantity = obx.QueryIntegerProperty<CartItem>(
    _entities[5].properties[1],
  );

  /// See [CartItem.name].
  static final name = obx.QueryStringProperty<CartItem>(
    _entities[5].properties[2],
  );

  /// See [CartItem.price].
  static final price = obx.QueryDoubleProperty<CartItem>(
    _entities[5].properties[3],
  );

  /// See [CartItem.menuItem].
  static final menuItem = obx.QueryRelationToOne<CartItem, Active_Table_view>(
    _entities[5].properties[4],
  );

  /// See [CartItem.reserved_field].
  static final reserved_field = obx.QueryStringProperty<CartItem>(
    _entities[5].properties[5],
  );

  /// See [CartItem.reserved_field1].
  static final reserved_field1 = obx.QueryStringProperty<CartItem>(
    _entities[5].properties[6],
  );

  /// See [CartItem.reserved_field2].
  static final reserved_field2 = obx.QueryStringProperty<CartItem>(
    _entities[5].properties[7],
  );

  /// See [CartItem.reserved_field3].
  static final reserved_field3 = obx.QueryStringProperty<CartItem>(
    _entities[5].properties[8],
  );

  /// See [CartItem.reserved_field4].
  static final reserved_field4 = obx.QueryStringProperty<CartItem>(
    _entities[5].properties[9],
  );

  /// See [CartItem.reserved_field5].
  static final reserved_field5 = obx.QueryStringProperty<CartItem>(
    _entities[5].properties[10],
  );
}

/// [OrderItem] entity fields to define ObjectBox queries.
class OrderItem_ {
  /// See [OrderItem.id].
  static final id = obx.QueryIntegerProperty<OrderItem>(
    _entities[6].properties[0],
  );

  /// See [OrderItem.name].
  static final name = obx.QueryStringProperty<OrderItem>(
    _entities[6].properties[1],
  );

  /// See [OrderItem.price].
  static final price = obx.QueryDoubleProperty<OrderItem>(
    _entities[6].properties[2],
  );

  /// See [OrderItem.table].
  static final table = obx.QueryRelationToOne<OrderItem, Active_Table_view>(
    _entities[6].properties[3],
  );

  /// See [OrderItem.quantity].
  static final quantity = obx.QueryIntegerProperty<OrderItem>(
    _entities[6].properties[4],
  );

  /// See [OrderItem.reserved_field].
  static final reserved_field = obx.QueryStringProperty<OrderItem>(
    _entities[6].properties[5],
  );

  /// See [OrderItem.reserved_field1].
  static final reserved_field1 = obx.QueryStringProperty<OrderItem>(
    _entities[6].properties[6],
  );

  /// See [OrderItem.reserved_field2].
  static final reserved_field2 = obx.QueryStringProperty<OrderItem>(
    _entities[6].properties[7],
  );

  /// See [OrderItem.reserved_field3].
  static final reserved_field3 = obx.QueryStringProperty<OrderItem>(
    _entities[6].properties[8],
  );

  /// See [OrderItem.reserved_field4].
  static final reserved_field4 = obx.QueryStringProperty<OrderItem>(
    _entities[6].properties[9],
  );

  /// See [OrderItem.reserved_field5].
  static final reserved_field5 = obx.QueryStringProperty<OrderItem>(
    _entities[6].properties[10],
  );
}

/// [Active_Table_view] entity fields to define ObjectBox queries.
class Active_Table_view_ {
  /// See [Active_Table_view.id].
  static final id = obx.QueryIntegerProperty<Active_Table_view>(
    _entities[7].properties[0],
  );

  /// See [Active_Table_view.number].
  static final number = obx.QueryIntegerProperty<Active_Table_view>(
    _entities[7].properties[1],
  );

  /// See [Active_Table_view.total].
  static final total = obx.QueryDoubleProperty<Active_Table_view>(
    _entities[7].properties[2],
  );

  /// See [Active_Table_view.paymentMethod].
  static final paymentMethod = obx.QueryStringProperty<Active_Table_view>(
    _entities[7].properties[3],
  );

  /// See [Active_Table_view.reserved_field].
  static final reserved_field = obx.QueryStringProperty<Active_Table_view>(
    _entities[7].properties[4],
  );

  /// See [Active_Table_view.reserved_field1].
  static final reserved_field1 = obx.QueryStringProperty<Active_Table_view>(
    _entities[7].properties[5],
  );

  /// See [Active_Table_view.reserved_field2].
  static final reserved_field2 = obx.QueryStringProperty<Active_Table_view>(
    _entities[7].properties[6],
  );

  /// See [Active_Table_view.reserved_field3].
  static final reserved_field3 = obx.QueryStringProperty<Active_Table_view>(
    _entities[7].properties[7],
  );

  /// See [Active_Table_view.reserved_field4].
  static final reserved_field4 = obx.QueryStringProperty<Active_Table_view>(
    _entities[7].properties[8],
  );

  /// See [Active_Table_view.reserved_field5].
  static final reserved_field5 = obx.QueryStringProperty<Active_Table_view>(
    _entities[7].properties[9],
  );

  /// see [Active_Table_view.orders]
  static final orders = obx.QueryBacklinkToMany<OrderItem, Active_Table_view>(
    OrderItem_.table,
  );
}
