import 'dart:io';
import 'package:flutter/widgets.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:objectbox/objectbox.dart';
import '../objectbox.g.dart'; // Generated by build_runner
import '../utilities.dart';
import 'package:provider/provider.dart';
import 'ObjectBoxService.dart';
import 'package:intl/intl.dart';
import 'package:file_picker/file_picker.dart';
// import 'package:external_path/external_path.dart';
// import 'package:permission_handler/permission_handler.dart';

class ObjectBoxManager {
  late Store store;
  late String _dbDirectoryPath;
  BuildContext? context;
 
   ObjectBoxManager({Key? key, this.context});

  /// Initialize the store
  Future<void> init() async {
    final store_path = AppConstants.objectbox_path;
    _dbDirectoryPath = store_path;
    // _dbDirectoryPath = store_path;
    // store = await openStore(directory: _dbDirectoryPath);
    // store = Provider.of<ObjectBoxService>(context, listen: false).store;
  }

  /// Create a Backup
  Future<String?> backupDatabase(BuildContext context, String backupPath) async {
    // 1. Get the Service (Not just the store, get the Service so we can update it later)
    final objectBoxService = Provider.of<ObjectBoxService>(context, listen: false);
    Store store = objectBoxService.store;

    try {
      // CRITICAL FIX: Capture path BEFORE closing the store
      final dbDirectoryPath = store.directoryPath;

      // 2. Close the store
      store.close();

      // 3. File Operations
      final srcFile = File(p.join(dbDirectoryPath, 'data.mdb'));
      if (!srcFile.existsSync()) {
        // Re-open if file missing (recovery)
        store = await openStore(directory: dbDirectoryPath);
        objectBoxService.store = store; // Update Provider
        return null;
      }

      final backupFile = File(backupPath);
      if (!await backupFile.parent.exists()) {
        await backupFile.parent.create(recursive: true);
      }

      await srcFile.copy(backupPath);

      // 4. Re-open the store
      store = await openStore(directory: dbDirectoryPath);
      
      // CRITICAL: Update the Provider with the new open store instance
      objectBoxService.store = store; 
      // If ObjectBoxService extends ChangeNotifier, call notifyListeners() inside it.

      return backupPath;
    } catch (e) {
      // print_log_red("Backup failed: $e");
      // print("Backup failed: $e");
      screen_massage(context, "Backup failed: $e");
      return null;
    }
  }

  /// Restore from Backup
  /// [backupFilePath] is the full path to your .mdb backup file
  Future<bool> restoreDatabase(BuildContext context, String backupFilePath) async {
    // 1. Get Service
    final objectBoxService = Provider.of<ObjectBoxService>(context, listen: false);
    Store store = objectBoxService.store;

    try {
      final backupFile = File(backupFilePath);
      if (!await backupFile.exists()) return false;

      // CRITICAL FIX: Capture path BEFORE closing
      final dbDirectoryPath = store.directoryPath;

      // 2. Close store
      store.close();

      // 3. Overwrite file
      final currentDbFile = File(p.join(dbDirectoryPath, 'data.mdb'));
      
      // Delete lock file if exists
      final lockFile = File(p.join(dbDirectoryPath, 'lock.mdb'));
      if (await lockFile.exists()) {
        await lockFile.delete();
      }

      await backupFile.copy(currentDbFile.path);

      // 4. Re-open store
      store = await openStore(directory: dbDirectoryPath);

      // CRITICAL: Update the Provider
      objectBoxService.store = store;

      return true;
    } catch (e) {
      // Recovery
      // store = await openStore(directory: ...);
      // objectBoxService.store = store;
      // print("Restore failed: $e");
      screen_massage(context, "Restore failed: $e");
      return false;
    }
  }



// Usage Example inside a Widget
void handleBackup(BuildContext context) async {
  // Define a location for the backup (e.g., app's temporary folder or external storage)
  // For external storage, you need 'manage external storage' permission on Android 11+
  // store = Provider.of<ObjectBoxService>(context, listen: false).store;
  final directory = await getDownloadFolder();
  print_log("Could not get downloads directory.$directory");

  // final directory = await getMediaFolderpath();
  print_log("directory ${directory}");
  if (directory == null) {
    print_log("Could not get downloads directory.");
    screen_massage(context, "Could not get downloads directory.");
    return;
  }
  
  final formattedDate = DateFormat('dd_MM_yyyy').format(DateTime.now());
  // final backupPath = p.join(directory, 'Orbipay Backup', 'backup_$formattedDate.mdb');
  final backupPath = p.join(directory,  'backup_$formattedDate.mdb');

  final resultPath = await backupDatabase(context,backupPath);
  
  if (resultPath != null) {
    print_log("Backup successful at $resultPath");
    screen_massage(context, "Backup successful at $resultPath");
    // You can now upload 'resultPath' to Google Drive, share it, etc.
  }
}

void handleRestore(BuildContext context) async {
  // 1. Let the user pick a file
  final result = await FilePicker.platform.pickFiles(
    type: FileType.custom,
    allowedExtensions: ['mdb'],
  );

  // 2. Check if the user cancelled the picker
  if (result == null || result.files.single.path == null) {
    print_log("File picking cancelled by user.");
    return;
  }

  // 3. Get the path of the selected file
  final backupPath = result.files.single.path!;
  print_log("Selected backup file: $backupPath");

  final store_path = AppConstants.objectbox_path;

  // 4. Proceed with the restore operation
  bool success = await restoreDatabase(context, backupPath);

  if (success) {
    print_log("Restore successful! UI should refresh.");
    screen_massage(context, "Restore successful! Please restart the app.");
  }
}












}